function pixelArea=CArea(Xhigh, Xlow, Y, r)
pixelArea=(0.5 * ((Xhigh * sqrt(r*r - Xhigh * Xhigh) + ...
    r*r * asin(Xhigh / r)) -...    
	 (Xlow * sqrt(r*r - Xlow * Xlow) + r*r * asin(Xlow / r))) -...
	 Y * (Xhigh - Xlow));